CREATE TABLE Departments 
(
	ID			INT NOT NULL PRIMARY KEY,
	Name		NVARCHAR(50) NOT NULL
)

CREATE TABLE Managers 
(
	ID			INT NOT NULL PRIMARY KEY,
	Surname		NVARCHAR(50) NOT NULL,
	Name		NVARCHAR(50) NOT NULL,
	Secname		NVARCHAR(50) NOT NULL,
	ID_main_dep INT,
	ID_sec_dep	INT,
	ID_chief	INT
)

CREATE TABLE Products 
(
	ID			INT NOT NULL PRIMARY KEY,
	Name		NVARCHAR(50) NOT NULL,
	Price		FLOAT  NOT NULL
)

CREATE TABLE Sales 
(
	ID			INT NOT NULL PRIMARY KEY IDENTITY,
	ID_manager	INT NOT NULL,
	ID_product	INT NOT NULL,
	Cnt			INT NOT NULL,
	Moment		DATETIME DEFAULT CURRENT_TIMESTAMP
)
