IF	0 < (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'SHOPS')
	DROP TABLE SHOPS ;

CREATE TABLE SHOPS(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(MAX) NOT NULL,
	[COUNTRYID] INT NOT NULL);

DECLARE @I INT
SET @I = 1

WHILE @I<300
BEGIN
	INSERT INTO SHOPS ([NAME],[COUNTRYID]) VALUES ( 
		CONCAT(N'Магазин № ', @I), 
		(SELECT TOP 1 ID FROM COUNTRIES ORDER BY NEWID() )
		)
	SET @I = @I + 1
END