IF	0 < (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'SALES')
	DROP TABLE SALES ;

CREATE TABLE SALES(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	[PRICE] MONEY NOT NULL,
	[QUANTITY] INT NOT NULL,
	[SALEDATE] DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[BOOKID] INT NOT NULL,
	[SHOPID] INT NOT NULL);

DECLARE @I INT
DECLARE @N INT
SET @I = 1

WHILE @I<2000
BEGIN
	SET @N = ( SELECT TOP 1 ID FROM BOOKS ORDER BY NEWID() )
	INSERT INTO SALES ([PRICE], [QUANTITY], [SALEDATE], [BOOKID], [SHOPID]) VALUES ( 
		(SELECT [PRICE] FROM BOOKS WHERE ID=@N),  -- [PRICE] 
		(ABS(CHECKSUM(NEWID())) % 20 + 1),  -- [QUANTITY]
		('2018-01-01' + DATEADD(day, (ABS(CHECKSUM(NEWID())) % 365), 0)+ DATEADD(hour, (ABS(CHECKSUM(NEWID())) % 24), 0)+ DATEADD(minute, (ABS(CHECKSUM(NEWID())) % 60), 0)),
		@N,  -- [BOOKID]
		( SELECT TOP 1 ID FROM SHOPS ORDER BY NEWID() )  -- [SHOPID]
		)
	SET @I = @I + 1
END